package com.experforms.generator.model

import org.springframework.data.annotation.CreatedDate
import org.springframework.data.annotation.Id
import org.springframework.data.annotation.LastModifiedDate
import org.springframework.data.mongodb.core.mapping.Document
import java.time.Instant

@Document(collection = "posts")
data class Post(
    @Id val id: String? = null, // The ID is nullable as it can be auto-generated by MongoDB
    val userId: String,
    val title: String,
    val content: String,
    val coverImage: String,

    @CreatedDate val createdAt: Instant? = null,  // Automatically set when created
    @LastModifiedDate val updatedAt: Instant? = null  // Automatically updated on modification
)
